### ISSUE TITLE
Usage of internal cross references in Asciidoc

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/website-adoptium-documentation#4]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

In the migration documentation (https://github.com/AdoptOpenJDK/website-adoptium-documentation/blob/main/migration/index.adoc) several links direct to the migration page of AdoptOpenJDK. Instead of doing so such links should be defined as [internal cross references in Asciidoc](https://docs.asciidoctor.org/asciidoc/latest/macros/xref/) since all this paragraphs are part of the same documentation file.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [x]  Fork the repository in github by simply clicking the 'fork' button.
- [x]  Check out the forked repository
- [x]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [x]  Commit your changes.
- [x]  Start a Pull Request.
- [x]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by CKeibel** [comment]
Hi I am interested in solving this issue.
